/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/HOODIEUP.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Hoodieup =(props)=> {
  const { nodes, materials } = useGLTF('./models/HOODIEUP.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[11.46, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.zip_up__hoodie4_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.zip_up__hoodie4_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.zip_up__hoodie4_3.geometry} material={materials['Material46799.001']} />
      </group>
    </group>
  )
}

export default Hoodieup;

useGLTF.preload('./models/HOODIEUP.glb')
