/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/HOODIEDOWN.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Hoodiedown = (props) => {
  const { nodes, materials } = useGLTF('./models/HOODIEDOWN.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.zip_up__hoodie3_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.zip_up__hoodie3_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.zip_up__hoodie3_3.geometry} material={materials['Material46799.001']} />
      </group>
    </group>
  )
}

export default Hoodiedown;

useGLTF.preload('./models/HOODIEDOWN.glb')
