/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/LETTERS.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Letras = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/LETTERS.glb')
  const { actions } = useAnimations(animations, group);
  {/*console.log(names);
  useEffect(() => {
  actions[names[0]].reset().fadeIn(0.5).play();
  }, []);*/}

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Curve002" geometry={nodes.Curve002.geometry} material={materials['Material.002']} position={[0, 0.27, -0.24]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Curve001" geometry={nodes.Curve001.geometry} material={materials['Material.001']} position={[0, 0.27, -0.24]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

export default Letras;

useGLTF.preload('./models/LETTERS.glb')
